# Generated by Django 5.2.4 on 2025-07-30 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_ad_user_exchangeproposal_ad_receiver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeproposal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('toys', 'Игрушки'), ('electronics', 'Электроника'), ('sports', 'Товары для спорта'), ('home', 'Товары для дома'), ('books', 'Книги и журналы'), ('clothes', 'Одежда'), ('other', 'Другое')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='condition',
            field=models.CharField(choices=[('new', 'Новый'), ('used', 'Б/у')], max_length=10, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_receiver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to='ads.ad', verbose_name='Желаемая вещь'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='ad_sender',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to='ads.ad', verbose_name='Предлагаемая вещь'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='comment',
            field=models.CharField(max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='exchangeproposal',
            name='status',
            field=models.CharField(choices=[('W', 'Ожидает'), ('Y', 'Принята'), ('N', 'Отклонена')], default='Ожидает', verbose_name='Статус'),
        ),
    ]
